function skillsMember() {
    var member = document.getElementById("member");
    var memberSkills = document.getElementById("member-skills");
    var memberSkillsButton = document.getElementById("member-skills-button");
    var memberSkillsButtonIcon = document.getElementById("member-skills-button-icon");
    var memberSkillsButtonIconClass = document.getElementById("member-skills-button-icon-class");
    var memberSkillsButtonIconClass2 = document.getElementById("member-skills-button-icon-class2");
    var memberSkillsButtonIconClass3 = document.getElementById("member-skills-button-icon-class3");
    var memberSkillsButtonIconClass4 = document.getElementById("member-skills-button-icon-class4");
    var memberSkillsButtonIconClass5 = document.getElementById("member-skills-button-icon-class5");
    var memberSkillsButtonIconClass6 = document.getElementById("member-skills-button-icon-class6");
    var memberSkillsButtonIconClass7 = document.getElementById("member-skills-button-icon-class7");
    var memberSkillsButtonIconClass8 = document.getElementById("member-skills-button-icon-class8");
    var memberSkillsButtonIconClass9 = document.getElementById("member-skills-button-icon-class9");
    var memberSkillsButtonIconClass10 = document.getElementById("member-skills-button-icon-class10");
    var memberSkillsButtonIconClass11 = document.getElementById("member-skills-button-icon-class11");
    var memberSkillsButtonIconClass12 = document.getElementById("member-skills-button-icon-class12");
    var memberSkillsButtonIconClass13 = document.getElementById("member-skills-button-icon-class13");
    var memberSkillsButtonIconClass14 = document.getElementById("member-skills-button-icon-class14");
    var memberSkillsButtonIconClass15 = document.getElementById("member-skills-button-icon-class15");
    var memberSkillsButtonIconClass16 = document.getElementById("member-skills-button-icon-class16");
    var memberSkillsButtonIconClass17 = document.getElementById("member-skills-button-icon-class17");
    var memberSkillsButtonIconClass18 = document.getElementById("member-skills-button-icon-class18");
    var memberSkillsButtonIconClass19 = document.getElementById("member-skills-button-icon-class19");
    var memberSkillsButtonIconClass20 = document.getElementById("member-skills-button-icon-class20");
    var memberSkillsButtonIconClass21 = document.getElementById("member-skills-button-icon-class21");
    var memberSkillsButtonIconClass22 = document.getElementById("member-skills-button-icon-class22");
    var memberSkillsButtonIconClass23 =